services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: energy
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  ingestion:
    build:
      context: ./ingestion-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./ingestion-api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cleaner

  cleaner:
    build:
      context: ./cleaning-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8100 --reload
    volumes:
      - ./cleaning-api:/code
    ports:
      - "8100:8100"

volumes:
  pgdata:
