services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: energy
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    # 資料庫記憶體配置
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  ingestion:
    build:
      context: ./ingestion-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./ingestion-api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cleaner
    # ingestion-api 記憶體配置
    deploy:
      resources:
        limits:
          memory: 512M      # 最大記憶體限制
          cpus: '1.0'       # CPU 限制
        reservations:
          memory: 256M      # 保證最小記憶體
          cpus: '0.5'       # 保證最小 CPU
    # 環境變數優化
    environment:
      - PYTHONUNBUFFERED=1
      # 注意：移除 WORKERS 和 MAX_CONNECTIONS，因為你的應用沒有使用這些變數
      - AUTH_SECRET_KEY=NTCUST-ENERGY-MONITOR
      - COMPATIBILITY_MODE=true
      - DEFAULT_ALLOWED_IPS=""

  cleaner:
    build:
      context: ./cleaning-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8100 --reload
    volumes:
      - ./cleaning-api:/code
    ports:
      - "8100:8100"
    depends_on:
      - db  # cleaner 可能也需要資料庫
    # 清洗服務記憶體配置
    deploy:
      resources:
        limits:
          memory: 1G        # 資料清洗可能需要更多記憶體
        reservations:
          memory: 512M

volumes:
  pgdata: